var user = {
login: "EricRClark",
id: 16374383,
avatar_url: "https://avatars.githubusercontent.com/u/16374383?v=3",
gravatar_id: "",
url: "https://api.github.com/users/EricRClark",
html_url: "https://github.com/EricRClark",
followers_url: "https://api.github.com/users/EricRClark/followers",
following_url: "https://api.github.com/users/EricRClark/following{/other_user}",
gists_url: "https://api.github.com/users/EricRClark/gists{/gist_id}",
starred_url: "https://api.github.com/users/EricRClark/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/EricRClark/subscriptions",
organizations_url: "https://api.github.com/users/EricRClark/orgs",
repos_url: "https://api.github.com/users/EricRClark/repos",
events_url: "https://api.github.com/users/EricRClark/events{/privacy}",
received_events_url: "https://api.github.com/users/EricRClark/received_events",
type: "User",
site_admin: false,
name: "Eric Clark",
company: "Iron Yard Charleston",
blog: null,
location: "Charleston, SC",
email: "eric.erandy@gmail.com",
hireable: null,
bio: null,
public_repos: 11,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2015-12-20T19:24:03Z",
updated_at: "2016-02-17T00:32:24Z"
}
